version: "3.9"  # optional since v1.27.0
services:
  game-server:
    hostname: "game-server-${CHANNEL}"
    image: "ghcr.io/cgsdev0/rollycubes:${CHANNEL}"
    volumes:
      - ../../secrets:/secrets
    environment:
      - CHANNEL
    external_links:
      - "auth:auth"
networks:
  default:
    name: rollycubes
    external: true

