version: '3.9'

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./nginx-certbot.env
    environment:
      CERTBOT_EMAIL: rollycubes@cgs.dev
    ports:
      - 80:80
      - 443:443
    external_links:
      - "auth:auth"
      - "game-server-prod:game-server-prod"
      - "game-server-beta:game-server-beta"
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./config:/etc/nginx/user_conf.d
      - ../client/beta:/var/www/client/beta
      - ../client/prod:/var/www/client/prod
  otel-collector:
    image: opentelemetry-collector-contrib
    external_links:
      - "postgres:postgres"
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension

volumes:
  nginx_secrets:
networks:
  default:
    name: rollycubes
    external: true
