name: Auth Server Docker

on:
  workflow_dispatch

env:
  REGISTRY: ghcr.io
  CHANNEL: latest
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: auth
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-auth:${{ env.CHANNEL }}

    # Deploy it
    - name: ssh-scp-ssh-pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@78e864b4890087a58248ff39320406971ca88b89
      with:
        host: rollycubes.com
        user: root
        key: ${{ secrets.DO_SSH_KEY }}
        first_ssh: |
          cd /root/auth
          docker-compose down || true
        # scp from local to remote
        scp: |
          auth/docker-compose.yml => '/root/auth'
        # execute post-commands after scp
        last_ssh: |
          cd /root/auth
          docker-compose --env-file ../secrets/.env up -d
