name: Deploy Auth Service to Digital Ocean

on:
  release:
    types: [ created ]

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    # Set up
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15.x'
        
    # Build server
    - run: ./build.sh
      working-directory: auth
    
    # Deploy it
    - name: ssh-scp-ssh-pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@78e864b4890087a58248ff39320406971ca88b89
      with:
        host: rollycubes.com
        user: root
        key: ${{ secrets.PROD_DEPLOY_KEY }}
        first_ssh: |
          sudo rm -rf /home/shane/auth-server
          systemctl stop dice_auth
        # scp from local to remote
        scp: |
          auth/build => '/home/shane/.'
        # execute post-commands after scp
        last_ssh: systemctl start dice_auth
