name: Deploy to Digital Ocean

on:
  release:
    types: [ created ]

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    # Set up
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15.x'
        
    # Build server + client
    - run: make release
    - run: yarn install && ( yarn build || echo "errors are delicious nom nom nom" )
      working-directory: client
    
    # Deploy it
    - name: ssh-scp-ssh-pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@78e864b4890087a58248ff39320406971ca88b89
      with:
        host: rollycubes.com
        user: root
        key: ${{ secrets.PROD_DEPLOY_KEY }}
        first_ssh: |
          sudo rm -rf /var/www/build
          systemctl stop dice
        # scp from local to remote
        scp: |
          GameServer => '/usr/bin/GameServer'
          client/build => '/var/www/.'
        # execute post-commands after scp
        last_ssh: systemctl start dice
