name: Deploy Auth Service to Digital Ocean

on:
  workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    # Set up
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15.x'
        
    # Build server
    - run: npm install; ./build.sh; mv build auth-server
      working-directory: auth
    
    - name: Deploy to server
      id: deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.PROD_DEPLOY_KEY}}
      with:
        flags: '-avzr'
        options: ''
        ssh_options: ''
        src: 'auth/auth-server'
        dest: 'root@rollycubes.com:/home/shane/.'
        
    # Restart the service
    - name: ssh-scp-ssh-pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@78e864b4890087a58248ff39320406971ca88b89
      with:
        host: rollycubes.com
        user: root
        key: ${{ secrets.PROD_DEPLOY_KEY }}
        first_ssh: systemctl start dice_auth
