name: Prebuild devcontainer

on:
  push:
    branches: [ "main" ]
    paths: [ '.github/.devcontainer/Dockerfile' ]
  workflow_dispatch: {}
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Pre-build dev container image
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/cgsdev0/rollycubes-devcontainer
        cacheFrom: ghcr.io/cgsdev0/rollycubes-devcontainer
        subFolder: .github
        push: always
